### ISSUE TITLE
width of messagelist be compressed when swipe down to check new mail

### ISSUE THREAD

**Issue by michaelchong2005** [johndoh/roundcube-swipe#1]
Thanks for your plugin. We setup a RC1.4b with this plugin for testing. We found a problem, when swipe down to check new email. the width of messagelist-content will be compressed.
Before swipe down:
![a](https://user-images.githubusercontent.com/8684499/51260915-4314f780-19ea-11e9-8873-2edbfc49c651.PNG)
After swipe down:
![b](https://user-images.githubusercontent.com/8684499/51260927-490ad880-19ea-11e9-8b29-5611e58601d7.PNG)

**Comment by johndoh** [comment]
i've noticed this too but the width goes back to normal once the swipe action is complete right? its something to do with translatey and flexbox i think. i might just change the way vertical swipes are displayed and not move the message list

**Comment by michaelchong2005** [comment]
aha, I found the root cause, just comment out this line.

https://github.com/johndoh/roundcube-swipe/blob/66f04815e607b9618ad0040333d393b33a469384/skins/elastic/swipe.less#L180

**Comment by johndoh** [comment]
latest commit reworks vertical actions, no more moving the message list so no problem with the width
