### ISSUE TITLE
delete action

### ISSUE THREAD

**Issue by grape6** [johndoh/roundcube-swipe#11]
On iPhone after swipe left (delete) next message is opened in full view.
May be it's better to stay in message list?

and there is no confirmation for delete action.

RCM git.

**Comment by johndoh** [comment]
please see https://github.com/roundcube/roundcubemail/issues/6795

do you have `display_next` (After message delete/move display the next message) enabled?

**Comment by grape6** [comment]
Thanks, option was enabled by default, my fault.
and what about delete confirmation, is it possible?

**Comment by johndoh** [comment]
confirmed as core issue so closing here.

this plugin does not implement its own delete action, it calls the one in the core. iirc that only displays confirmation only on permanent delete. imo having to confirm when moving a message to trash would be annoying esp in something like this plugin who's purpose is to provide a quick way to perform basic tasks on mobiles.
