### ISSUE TITLE
Does not work in duplicated elastic theme

### ISSUE THREAD

**Issue by Alseenrodelap** [johndoh/roundcube-swipe#17]
Hi,

I duplicated the Elastic theme and renamed it. All is working, except for this plugin while everything within the theme remains the same.
I did this to prevent changes getting lost on an update.

**Comment by johndoh** [comment]
Do you mean you extended the Elastic skin or you created a brand new skin? If you created a brand new skin then did you create a corresponding skin folder within this plugin?

**Comment by johndoh** [comment]
no feedback
