### ISSUE TITLE
no variable @fa-var-fire-alt 

### ISSUE THREAD

**Issue by michaelchong2005** [johndoh/roundcube-swipe#2]
I think the correct variable is @fa-var-fire.

https://github.com/johndoh/roundcube-swipe/blob/66f04815e607b9618ad0040333d393b33a469384/skins/elastic/swipe.less#L160

**Comment by johndoh** [comment]
see https://github.com/roundcube/roundcubemail/commit/b85c5b3b7a491d840ef5005f798d4f5aa38fb471
