### ISSUE TITLE
Archive not working

### ISSUE THREAD

**Issue by Offerel** [johndoh/roundcube-swipe#25]
I have configured 'archive' for right swipe, but it does not work. Nothing happens, when i swipe to the right. Archive plugin is enabled and working. Any ideas?

**Comment by johndoh** [comment]
When you said nothing happens do you mean the row slides and the action activates (turns yellow) but the message is not moved or do you mean the row does not slide?

What version of Roundcube and what version of the plugin?

I think there is a typo in the config name any way so try this:

```diff
--- a/swipe.php
+++ b/swipe.php
@@ -40,7 +40,7 @@ class swipe extends rcube_plugin
                 'checkmail' => ['label' => 'checkmail'],
             ],
             'horizontal' => [
-                'archive' => ['label' => 'archive.buttontext', 'plugin' => true, 'condition' => 'config:archive_folder !== false'],
+                'archive' => ['label' => 'archive.buttontext', 'plugin' => true, 'condition' => 'config:archive_mbox !== false'],
                 'delete' => ['label' => 'delete'],
                 'forward' => ['label' => 'forward'],
                 'markasjunk' => ['label' => 'markasjunk.markasjunk', 'plugin' => true],
```

**Comment by Offerel** [comment]
I mean, it does not swipe at all. I'm partially on 1.6-rc, since I'm [re-writing](https://codeberg.org/Offerel/roundcube_primitivenotes/src/branch/v2.1.0) my PrimitiveNotes plugin for this RC version. But your change is working (in both RC 1.5.x ad 1.6-rc). I have removed the condition completely for testing purposes what worked also in my case.  But it is better with the condition. Many thx.
