### ISSUE TITLE
Hold and select

### ISSUE THREAD

**Issue by melroy89** [johndoh/roundcube-swipe#29]
I now this is a roundcube-swipe plugin.. But hear me out..

What about a nice roundcube-hold-select for mobile plugin? So just selecting and hold your finger on a contact or email will automatically mark it as selected....

I think you have the knowledge to bring this idea into reality, without not too much work hopefully.. 🥳 

What do you think about my plugin proposal?

**EDIT**: Did I already mentioned I love your plugins?! All of them! Including the swipe, taskwatermark & contextmenu. 👏🏽

**Comment by johndoh** [comment]
This is outside the scope of this plugin which offers select via swipe action

**Comment by melroy89** [comment]
I know. But you might want to consider adding this small improvement in a another dedicated plugin
