### ISSUE TITLE
in less than a screen, the message list is stretched to full screen

### ISSUE THREAD

**Issue by michaelchong2005** [johndoh/roundcube-swipe#3]
need comment out this line.
https://github.com/johndoh/roundcube-swipe/blob/66f04815e607b9618ad0040333d393b33a469384/skins/elastic/swipe.less#L181

**Comment by johndoh** [comment]
i couldnt recreate this. may be you had removed the display: block; line like you mentioned https://github.com/johndoh/roundcube-swipe/issues/1#issuecomment-455051907 here. In any case I think 2b3cc00 means this is a non issue now
