### ISSUE TITLE
contradictory expression

### ISSUE THREAD

**Issue by michaelchong2005** [johndoh/roundcube-swipe#6]
Is this expression contradictory? and line 227 is the same.
`changeX < 5 && changeX > -5`

https://github.com/johndoh/roundcube-swipe/blob/0b2eecc39733a09b836d944142ec20529732a7c4/swipe.js#L224

**Comment by johndoh** [comment]
Inelegant perhaps but I don't think contradictory. I could use something like Math.abs() do make sure the val is always positive and simplify the checks.

**Comment by michaelchong2005** [comment]
I mean this paragraph 'changeX < 5 && changeX > -5', do you think so?

**Comment by johndoh** [comment]
that simply means that changeX has to be between -4 and 4

**Comment by johndoh** [comment]
done in git master
