### ISSUE TITLE
scroll when swipe left/right on iphone

### ISSUE THREAD

**Issue by michaelchong2005** [johndoh/roundcube-swipe#7]
I touched the list on iphone, when swipe left/right shown, it still scroll up/down in same time. It seems that those code can not woking well.

https://github.com/johndoh/roundcube-swipe/blob/0b2eecc39733a09b836d944142ec20529732a7c4/swipe.js#L182

**Comment by johndoh** [comment]
PR welcome

**Comment by johndoh** [comment]
please retest with git-master

**Comment by michaelchong2005** [comment]
still happen.
![video_2019-03-11_18-36-25~4](https://user-images.githubusercontent.com/8684499/54118328-b0169d80-442d-11e9-88f1-5097019ca1c7.gif)

**Comment by johndoh** [comment]
did 7d7d5eb71f0bfa2cc865b4e27a5bb91f5641befb help?

**Comment by johndoh** [comment]
i think this is fixed so closing. please reopen if not.
