### ISSUE TITLE
Vertical scroll breaks when not at top of message list

### ISSUE THREAD

**Issue by HaydenKatz** [johndoh/roundcube-swipe#8]
Using Elastic theme.

Issue only present when swipe down function is defined.

When I first load the page and I'm at the top of the message list, swipe down (refresh), left (delete) and right (select) work as expected.
Scroll capability also works until I release my finger with the message list not scrolled to top.

At this point, attempting to scroll only swipes left/right on the selected message, the message list no longer scrolls.

Sometimes I can scroll down (swipe up), and this will allow me to scroll up as long as I don't release my finger. This does not work when already at the bottom of the page though.

**Comment by johndoh** [comment]
fixed
